name: car_sae_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

platforms:
  android:
  ios:
  web:
  linux:
  windows:
  macos:

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.2.1
  mellowtel: ^0.0.4
  http: ^1.0.0
  path_provider: ^2.1.3
  permission_handler: ^10.3.6
  provider: ^6.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mime: ^1.0.5
  dio: ^5.4.3+1
  fl_chart: ^0.68.0
  flutter_colorpicker: ^1.0.0
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^5.2.0
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.20
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  chat_bubbles: ^1.6.0
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.0.0
  animated_splash_screen: ^1.3.0
  flutter_lints: ^4.0.0
  rive: ^0.12.0 
  flutter_animate: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  loggy: ^2.0.3
  go_router: ^11.1.3
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  flutter_chat_ui: ^1.6.12
  uuid: ^4.3.3
  flutter_chat_types: ^3.6.2
  flutter_secure_storage: ^4.2.1
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  file_picker: ^6.1.1
  pdf_gemini: ^0.0.3
  syncfusion_flutter_pdf: 
  google_generative_ai:
  google_gemini:
  flutter_gemini:
  google_fonts:
  syncfusion_flutter_pdfviewer:
  flutter_markdown:
  sizer: ^3.0.4
  firebase_auth:
  shared_preferences:
  intl:
  url_launcher:
  flutter_spinkit: ^5.1.0 

flutter_icons:
  # image_path: "assets/app_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  # assets:
  #   - assets/s1.png
  #   - assets/s2.png
  #   - assets/robocat.riv
  #   - assets/fonts/
  #   - assets/images/
  #   - assets/animations/

  # Optional: Customize fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700