// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8FDFXgW-h7mgXE21F3Y3lOfLcNby0ssw',
    appId: '1:465031831392:web:d7ee67c05acb6719a5c805',
    messagingSenderId: '465031831392',
    projectId: 'saeapp-68f85',
    authDomain: 'saeapp-68f85.firebaseapp.com',
    storageBucket: 'saeapp-68f85.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa8Pa4ApLoICaGKVuu_5-JWJCvJz7aVJI',
    appId: '1:465031831392:android:2a344f65db537373a5c805',
    messagingSenderId: '465031831392',
    projectId: 'saeapp-68f85',
    storageBucket: 'saeapp-68f85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1kNFVA0ZrAE_r83gns41sUR4X30OREeM',
    appId: '1:465031831392:ios:3778cc6e454659aea5c805',
    messagingSenderId: '465031831392',
    projectId: 'saeapp-68f85',
    storageBucket: 'saeapp-68f85.firebasestorage.app',
    iosBundleId: 'com.example.carSaeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1kNFVA0ZrAE_r83gns41sUR4X30OREeM',
    appId: '1:465031831392:ios:3778cc6e454659aea5c805',
    messagingSenderId: '465031831392',
    projectId: 'saeapp-68f85',
    storageBucket: 'saeapp-68f85.firebasestorage.app',
    iosBundleId: 'com.example.carSaeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8FDFXgW-h7mgXE21F3Y3lOfLcNby0ssw',
    appId: '1:465031831392:web:b98e1cf4ccc4f948a5c805',
    messagingSenderId: '465031831392',
    projectId: 'saeapp-68f85',
    authDomain: 'saeapp-68f85.firebaseapp.com',
    storageBucket: 'saeapp-68f85.firebasestorage.app',
  );
}
