class Query {
  String queryGenerator(
    String extractedText,
    String queryControllerText,
  ) {
    String query = '''

I will give you some data, which will include a text, and a question related to a text:

I would want you to please, make a JSON response, and dont respond with markdown, just pure string, but a string of a large JSON response, which will have a structutre like this:

{
    questionResult: ""
    citations: [
            {  
                "actual_citation": "Actual Line of Citation",
                "previous_line": "A line before the actual citation",
                "next_line": "A next to the actual citation",
            }
            {  
                "actual_citation": "Actual Line of Citation",
                "previous_line": "A line before the actual citation",
                "next_line": "A next to the actual citation",
            }
            {  
                "actual_citation": "Actual Line of Citation",
                "previous_line": "A line before the actual citation",
                "next_line": "A next to the actual citation",
            }

        ]
}

text from which the citations will be generated: $extractedText, make sure you generate atleast 1 citation each time

the question for which the questionResult will be generated based on the given text: $queryControllerText

the answer of the question which will go inside "questionResult" should be generated by you, you just need to use the given text as an argument, and just generate the json.
      

!important, Never return something like this:
"I apologize, but the provided text does not contain information about how streams differ from asynchronous data in terms of data delivery. Therefore, I cannot
generate an answer to your question.", "Just generate some questionResult, if you dont find any context from the provided text, and for citations, return previous and next line null, and the actual line as "No citations found" "


    ''';

    return query;
  }
}
